import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";
import LogoutBtn from "./../components/LogoutBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const logged_user = cookies().get("sid")?.value;

  function parseUser() {
    if (!logged_user) return undefined;
    return JSON.parse(logged_user);
  }

  const user = parseUser();

  return (
    <html lang="en">
      <body>
        <nav className="p-4 shadow bg-white text-black mb-4 flex justify-between items-center">
          <span>
            {user ? user.firstName + " " + user.lastName : "Unknown User"}
          </span>
          {user && (
            <>
              <LogoutBtn />
            </>
          )}
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
